### ISSUE TITLE
Discord Rich Presence Statuses

### ISSUE THREAD

**Issue by Frontesque** [Radiicall/jellyfin-rpc#121] opened 2024-07-09 21:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Ideally, the RPC app should be able to automatically detect if the media library that you are currently using is "Movies", "Shows" or "Music" and change to Discord's "Watching" or "Listening to" statuses respectively

### Describe alternatives you've considered

Alternatively, you should be able to set a flag in the config to only use one of the alternative statuses.

**Comment by Radiicall** [comment] 2024-07-10 11:37
Duplicate of #16 #60 and #98

**Closed by Radiicall** 2024-07-10 11:37 UTC
Labels: enhancement
