### ISSUE TITLE
Discord status option

### ISSUE THREAD

**Issue by CyberNeonHD** [Radiicall/jellyfin-rpc#98] opened 2024-01-20 00:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing feature requests

### Currently
- Discord only shows "Playing YourAppName"
- When clicking on your profile it will show:
![image](https://github.com/Radiicall/jellyfin-rpc/assets/50114712/53195f00-834c-4660-ad64-02ccab04b4cf)

### Feature Idea
- It would be cool to have an option in the config where we can choose between "Playing" and "Listening to"
- Also when Discord shows the status "Listening to", it will look like this when you inspect the profile:
![image](https://github.com/Radiicall/jellyfin-rpc/assets/50114712/cba707f7-d97c-4168-907d-9e1a009c7b3c)
- This is cleaner when you actually listen to music, hence this request :D.

**Comment by angelolz** [comment] 2024-01-22 04:50
I think this is a limitation of Discord RPC. Discord Rich Presence only shows the playing status for users. The "Listening to" status is reserved for the Spotify integration.

**Comment by MeronNagy** [comment] 2024-01-22 21:42
Not possible as of right now.
https://discord.com/developers/docs/game-sdk/activities#:~:text=Gateway%20documentation.-,ActivityType,will%20be%20discarded%20and%20will%20not%20change%20anything%20in%20the%20client.,-ActivityJoinRequestReply%20Enum

I tried sending a request with type 3 - Watching (See below) and it still displays as "Playing a game" (Screenshot)
```
{
  "args": {
    "activity": {
      "assets": {
        "large_image": "https://i.imgur.com/oX6vcds.png",
        "large_text": "Jellyfin-RPC v0.15.5",
        "small_image": "https://i.imgur.com/wlHSvYy.png",
        "small_text": "Paused"
      },
      "buttons": [
        {
          "label": "AniDB",
          "url": "https://anidb.net/episode/250978"
        },
        {
          "label": "IMDb",
          "url": "https://www.imdb.com/title/tt16988612"
        }
      ],
      "details": "My Dress-Up Darling",
      "state": "S1E4 Are These Your Girlfriend's?",
      "type": 3
    },
    "pid": 41553
  },
  "cmd": "SET_ACTIVITY",
  "nonce": "057a18c3-9f97-41d6-afd3-f8e1cf3d97e0"
}
```

<img width="314" alt="image" src="https://github.com/Radiicall/jellyfin-rpc/assets/24290882/c11190fe-eb83-4990-a60c-3fb472f242bd">

I also tried type 4 - Custom which will simply not display anything at all.

**Comment by Radiicall** [comment] 2024-01-22 22:08
Duplicate of #16 #60

**Closed** 2024-01-22 22:09 UTC
Labels: enhancement
